//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishesGo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeDetails
    {
        public int recipe_id { get; set; }
        public string recipe_title { get; set; }
        public string recipe_description { get; set; }
        public byte[] recipe_photo { get; set; }
        public Nullable<int> time_prepare { get; set; }
        public Nullable<int> calories { get; set; }
        public Nullable<System.DateTime> posting_date { get; set; }
        public Nullable<int> user_id { get; set; }
        public byte[] user_photo { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string nickname { get; set; }
        public Nullable<int> kitchen_id { get; set; }
        public string kitchen_title { get; set; }
        public string kitchen_description { get; set; }
        public Nullable<int> type_id { get; set; }
        public string recipe_type_title { get; set; }
    }
}
