//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishesGo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public int recipe_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public byte[] recipe_photo { get; set; }
        public Nullable<int> time_prepare { get; set; }
        public Nullable<int> calories { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> kitchen_id { get; set; }
        public Nullable<int> type_id { get; set; }
    
        public virtual Kitchens Kitchens { get; set; }
        public virtual RecipeTypes RecipeTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
