//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishesGo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngredientsView
    {
        public int recipe_id { get; set; }
        public string recipe_title { get; set; }
        public int ingredient_id { get; set; }
        public string ingredient_name { get; set; }
        public string quantity { get; set; }
    }
}
