//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishesGo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int subscription_id { get; set; }
        public Nullable<int> subscriber_id { get; set; }
        public Nullable<int> target_user_id { get; set; }
    
        public virtual Users User { get; set; }
        public virtual Users User1 { get; set; }
    }
}
